services:
  db:
    image: mysql:8.0
    container_name: myStoreAPI
    restart: always
    environment:
      MYSQL_DATABASE: myStoreAPI_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Esta línea es CLAVE: mapea tu script a la carpeta de inicio de MySQL
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - barberia-network

networks:
  barberia-network:
    driver: bridge

volumes:
  db_data: